server:
    port: 9090

spring:
    application:
        name: gateway-service

    profiles:
        active: dev

    redis:
        host: ${redisHost}
        port: ${redisPort}
        password: ${redisPassword}
        database: ${redisDatabase}

eureka:
    instance:
        prefer-ip-address: true
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://127.0.0.1:8761/eureka


t3t:
    secret:
        key: ${jwtSecretKey}